# This is work flow name
 name: Hello workflow

# Runs on trigger 
 on:
   push:
     branches: [main]

# jobs inside workflow
 jobs:

# NAME OF WORKFLOW job

# NAME OF WORKFLOW job

  greet:
# This is github runner  each job runs on it  
    runs-on: ubuntu-22.04 
    steps:
    - name: say hello to users
      run: echo "hello all"
    - name: say hello to username
      run: echo "Hello $USER"
  details:
    runs-on: ubuntu-22.04
    steps:
    - name: version of python
      run: python --version
